version: "3"

services:
  buy-server:
    container_name: NODEJS_SERVER_SALES
    build: "."
    volumes:
      - ./src:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: customnet
